### ISSUE TITLE
paragraph mark causes the script interpreter to break

### ISSUE THREAD

**Issue by aculich** [aculich/jetstream-setup#2]
Per @jlf603 (Jeremy Fischer)

Hiya — in https://raw.githubusercontent.com/aculich/jetstream-setup/master/jetstream-setup.sh --> can you remove that weird paragraph mark at the end of line 33? ```## Recommended extra packages for Trusty 14.04¶``` Apparently it causes the script interpreter to break on Jetstream. They’ve put in a ticket to fix it but the user (@jhaber-zz) that’s trying to use it won’t work unless he stops using the script.

Also, @iamciera this should fix the problem for you as well, I think.

**Comment by jhaber** [comment]
I believe you mentioned the wrong jhaber?

**Comment by aculich** [comment]
@jhaber oops, sorry, yeah I meant @jhaber-zz

**Comment by aculich** [comment]
@jhaber-zz @iamciera  this should fix the startup script problems that you are experiencing.

@jlf603 i think these scripts used to work just fine with the paragraph mark, so I am guessing that the issue is related to some sort of local/UTF problem.... maybe if there has been an upgrade recently in the ansible scripts or other system configurations?

Removing the paragraph mark will fix the problem for now, but i'll keep this in mind for other scripts with weird characters that could cause problems.

For posterity's sake, here is the error message that @iamciera sent me earlier:

1. When I include the ssh script when launching the instance I get this deployment error:
```
IMPORTANT NOTE: After deploying your instance, there was a problem with the SSH key or boot script included on this instance.
Included error message:
Error Traceback:Traceback (most recent call last):
  File "/opt/env/atmo_v28/local/lib/python2.7/site-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/env/atmo_v28/local/lib/python2.7/site-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "service/tasks/driver.py", line 942, in _deploy_instance_for_user
    _deploy_instance_for_user.retry(exc=exc)
  File "/opt/env/atmo_v28/local/lib/python2.7/site-packages/celery/app/task.py", line 668, in retry
    raise_with_context(exc)
  File "service/tasks/driver.py", line 937, in _deploy_instance_for_user
    user_deploy(instance.ip, username, instance_id, first_deploy=first_deploy)
  File "service/deploy.py", line 292, in user_deploy
    return raise_playbook_errors(playbook_runner, instance_id, instance_ip, hostname)
  File "service/deploy.py", line 549, in raise_playbook_errors
    raise AnsibleDeployException(msg)
AnsibleDeployException: Instance: faf09f26-b76f-4cc7-8fcd-3d6794f9c1e7 IP:149.165.169.78 Hostname: js-169-78.jetstream-cloud.org - failed with PlayBook(s) => {('Playbook: /opt/dev/atmosphere-ansible/ansible/playbooks/user_deploy/10_post_boot.yml', u'Role: atmo-user-boot-scripts', u'Task: bootscript_2 - copy scripts to script directory'): {'failures': 1}}
```

**Comment by iamciera** [comment]
Thanks @aculich,  I removed the symbol and the instance deployed without the error.  Looks like you updated the script too.
